import com.formdev.flatlaf.FlatDarkLaf
import java.awt.Color
import java.awt.Font
import java.lang.Exception
import java.util.ArrayList
import javax.swing.UIManager

/**
 * Generate a list of UIManager color keys.
 */
object UIManagerColorKeys {
    @Throws(Exception::class)
    @JvmStatic
    fun main(args: Array<String>) {
        FlatDarkLaf.setup()
        val colorKeys: MutableList<String?> = ArrayList<String?>()
        val entries = UIManager.getLookAndFeelDefaults().entries
        for (entry in entries) {
            if (entry.value is Color) {
                colorKeys.add(entry.key as String?)
            }
        }

        // print the color keys
        for (colorKey in colorKeys) {
            println(colorKey)
        }
    }
}

/**
 * DesktopIcon.foreground
 * List.selectionInactiveBackground
 * SplitPaneDivider.draggingColor
 * TabbedPane.closePressedBackground
 * TableHeader.focusCellBackground
 * Tree.selectionInactiveForeground
 * MenuBar.shadow
 * SplitPane.shadow
 * TabbedPane.focusColor
 * Button.highlight
 * ToggleButton.disabledSelectedBackground
 * TableHeader.hoverBackground
 * PasswordField.placeholderForeground
 * Separator.shadow
 * TextField.selectionForeground
 * ToggleButton.light
 * ToggleButton.pressedBackground
 * EditorPane.inactiveBackground
 * HelpButton.hoverBackground
 * TabbedPane.contentAreaColor
 * ComboBox.selectionBackground
 * Menu.icon.arrowColor
 * TextField.disabledBackground
 * Tree.icon.closedColor
 * TabbedPane.shadow
 * MenuItem.foreground
 * CheckBox.icon.disabledBackground
 * TabbedPane.highlight
 * TextField.foreground
 * Menu.foreground
 * ComboBox.buttonDarkShadow
 * TabbedPane.background
 * MenuBar.foreground
 * Spinner.buttonHoverArrowColor
 * Button.toolbar.hoverBackground
 * ComboBox.disabledBackground
 * ScrollBar.pressedThumbColor
 * PopupMenu.foreground
 * HelpButton.hoverBorderColor
 * TitlePane.buttonPressedBackground
 * RootPane.inactiveBorderColor
 * List.selectionInactiveForeground
 * PasswordField.revealIconColor
 * ToolBar.dockingBackground
 * CheckBox.icon.pressedBorderColor
 * ToolBar.separatorColor
 * ScrollBar.thumbShadow
 * controlHighlight
 * RadioButton.background
 * Table.selectionBackground
 * RootPane.foreground
 * EditorPane.inactiveForeground
 * ToolBar.highlight
 * textHighlight
 * Tree.background
 * Component.focusColor
 * menuText
 * Menu.acceleratorSelectionForeground
 * CheckBox.icon[filled].pressedSelectedBackground
 * Button.default.borderColor
 * menu
 * ToolBar.darkShadow
 * ScrollBar.buttonArrowColor
 * ComboBox.background
 * Button.default.hoverBackground
 * Viewport.foreground
 * ComboBox.buttonSeparatorColor
 * InternalFrame.borderColor
 * CheckBoxMenuItem.background
 * Panel.foreground
 * RadioButton.disabledText
 * ComboBox.disabledForeground
 * TextPane.caretForeground
 * controlLtHighlight
 * CheckBox.icon.disabledBorderColor
 * TitlePane.closePressedForeground
 * ToolBar.dockingForeground
 * InternalFrame.inactiveTitleForeground
 * TabbedPane.buttonPressedBackground
 * EditorPane.disabledBackground
 * ScrollBar.thumbHighlight
 * Spinner.buttonArrowColor
 * Objects.Purple
 * Tree.icon.leafColor
 * RadioButton.foreground
 * Slider.foreground
 * Actions.Blue
 * FormattedTextField.placeholderForeground
 * inactiveCaption
 * ComboBox.buttonEditableBackground
 * Tree.foreground
 * controlText
 * ScrollBar.thumbDarkShadow
 * window
 * FormattedTextField.selectionForeground
 * ScrollBar.thumb
 * ScrollPane.foreground
 * textHighlightText
 * CheckBox.icon.focusedBorderColor
 * MenuItem.background
 * ToggleButton.darkShadow
 * ToggleButton.tab.disabledUnderlineColor
 * TextPane.background
 * Button.default.focusedBorderColor
 * ToggleButton.tab.focusBackground
 * MenuBar.background
 * CheckBox.icon.hoverBorderColor
 * CheckBoxMenuItem.foreground
 * Label.disabledShadow
 * MenuItem.underlineSelectionCheckBackground
 * RadioButtonMenuItem.acceleratorForeground
 * CheckBox.icon.checkmarkColor
 * CheckBox.icon.background
 * Separator.foreground
 * windowText
 * CheckBox.icon.pressedBackground
 * RootPane.background
 * Component.error.borderColor
 * TextPane.inactiveBackground
 * ScrollBar.trackHighlight
 * TitlePane.embeddedForeground
 * Button.default.background
 * CheckBox.icon[filled].hoverSelectedBackground
 * ProgressBar.selectionBackground
 * MenuBar.hoverBackground
 * Button.shadow
 * TextPane.foreground
 * Viewport.background
 * ScrollBar.hoverThumbColor
 * MenuItem.acceleratorForeground
 * Panel.background
 * Slider.trackValueColor
 * Slider.hoverThumbColor
 * SplitPane.highlight
 * MenuItem.underlineSelectionBackground
 * TextField.placeholderForeground
 * TableHeader.pressedBackground
 * SplitPaneDivider.gripColor
 * TextArea.caretForeground
 * TitlePane.closePressedBackground
 * HelpButton.pressedBackground
 * Actions.Green
 * activeCaptionText
 * TableHeader.separatorColor
 * InternalFrame.inactiveTitleBackground
 * inactiveCaptionText
 * ColorChooser.swatchesDefaultRecentColor
 * Button.disabledSelectedBackground
 * TabbedPane.disabledUnderlineColor
 * Slider.background
 * Slider.disabledTrackColor
 * TextPane.inactiveForeground
 * Label.disabledForeground
 * Actions.Red
 * FormattedTextField.selectionBackground
 * controlShadow
 * Button.default.foreground
 * Actions.Grey
 * RadioButtonMenuItem.acceleratorSelectionForeground
 * MenuItem.disabledForeground
 * ScrollPane.background
 * ProgressBar.selectionForeground
 * TabbedPane.buttonHoverBackground
 * Actions.GreyInline
 * PasswordField.caretForeground
 * InternalFrame.inactiveBorderColor
 * Button.pressedBackground
 * TitledBorder.titleColor
 * SplitPaneDivider.oneTouchHoverArrowColor
 * HelpButton.disabledQuestionMarkColor
 * Button.borderColor
 * TitlePane.inactiveBackground
 * TextArea.foreground
 * ComboBox.buttonShadow
 * Objects.Blue
 * ToggleButton.toolbar.hoverBackground
 * Spinner.buttonDisabledArrowColor
 * textInactiveText
 * Objects.Pink
 * Tree.selectionForeground
 * ToolBar.shadow
 * Separator.background
 * TextPane.disabledBackground
 * MenuBar.highlight
 * ToolBar.floatingForeground
 * Component.borderColor
 * PasswordField.inactiveForeground
 * CheckBox.disabledText
 * SplitPaneDivider.oneTouchPressedArrowColor
 * Objects.YellowDark
 * Spinner.disabledForeground
 * Spinner.buttonDisabledSeparatorColor
 * ColorChooser.foreground
 * ComboBox.buttonDisabledSeparatorColor
 * ComboBox.buttonHoverArrowColor
 * Spinner.buttonSeparatorColor
 * InternalFrame.activeTitleBackground
 * Popup.dropShadowColor
 * Table.cellFocusColor
 * ComboBox.buttonDisabledArrowColor
 * ScrollBar.buttonDisabledArrowColor
 * ToggleButton.tab.hoverBackground
 * TableHeader.foreground
 * ToolBar.gripColor
 * ToggleButton.toolbar.selectedBackground
 * Button.default.focusColor
 * TitlePane.inactiveForeground
 * Button.darkShadow
 * Spinner.buttonPressedArrowColor
 * ToggleButton.foreground
 * textText
 * SplitPane.darkShadow
 * TabbedPane.disabledForeground
 * ComboBox.buttonBackground
 * Menu.selectionBackground
 * Actions.Yellow
 * TextField.caretForeground
 * List.selectionForeground
 * RadioButtonMenuItem.background
 * Objects.RedStatus
 * Tree.icon.expandedColor
 * Slider.focus
 * InternalFrame.activeTitleForeground
 * RadioButtonMenuItem.disabledForeground
 * HelpButton.background
 * Button.default.hoverBorderColor
 * ProgressBar.foreground
 * InternalFrame.borderLight
 * TabbedPane.closeForeground
 * PopupMenu.hoverScrollArrowBackground
 * RadioButtonMenuItem.selectionForeground
 * Button.selectedForeground
 * TextArea.background
 * inactiveCaptionBorder
 * HelpButton.borderColor
 * TitlePane.background
 * TextField.highlight
 * List.cellFocusColor
 * Tree.selectionBackground
 * Objects.Grey
 * ToolBar.background
 * RadioButton.shadow
 * ToolBar.floatingBackground
 * TextPane.selectionBackground
 * PasswordField.inactiveBackground
 * List.foreground
 * Menu.selectionForeground
 * TextArea.selectionForeground
 * Spinner.disabledBackground
 * Separator.highlight
 * ColorChooser.background
 * RadioButtonMenuItem.foreground
 * Objects.Green
 * Table.background
 * Objects.Red
 * TabbedPane.hoverColor
 * ToggleButton.highlight
 * ScrollBar.track
 * Tree.textBackground
 * TextArea.inactiveForeground
 * Component.custom.borderColor
 * Component.warning.borderColor
 * PopupMenu.scrollArrowColor
 * TableHeader.background
 * InternalFrame.buttonPressedBackground
 * CheckBoxMenuItem.acceleratorForeground
 * TextField.light
 * ScrollBar.hoverButtonBackground
 * TabbedPane.darkShadow
 * Table.focusCellForeground
 * TitlePane.foreground
 * HelpButton.disabledBackground
 * HelpButton.disabledBorderColor
 * Tree.selectionBorderColor
 * ToolBar.foreground
 * ToggleButton.background
 * CheckBox.icon[filled].selectedBorderColor
 * ToolTip.foreground
 * Slider.trackColor
 * CheckBox.icon[filled].selectedBackground
 * TextPane.selectionForeground
 * EditorPane.caretForeground
 * CheckBoxMenuItem.disabledForeground
 * Slider.focusedColor
 * MenuItem.acceleratorSelectionForeground
 * List.selectionBackground
 * HelpButton.questionMarkColor
 * InternalFrame.buttonHoverBackground
 * RadioButton.highlight
 * ToggleButton.toolbar.pressedBackground
 * TabbedPane.inactiveUnderlineColor
 * Table.foreground
 * Table.selectionInactiveBackground
 * MenuBar.borderColor
 * ProgressBar.background
 * Component.error.focusedBorderColor
 * CheckBox.icon.focusedBackground
 * Tree.hash
 * Button.background
 * ToolBar.light
 * PasswordField.selectionForeground
 * Slider.disabledThumbColor
 * ComboBox.buttonArrowColor
 * Tree.textForeground
 * RadioButtonMenuItem.selectionBackground
 * CheckBox.icon.selectedBorderColor
 * Button.selectedBackground
 * Table.sortIconColor
 * EditorPane.selectionForeground
 * InternalFrame.borderShadow
 * CheckBoxMenuItem.icon.checkmarkColor
 * activeCaptionBorder
 * ToggleButton.disabledBackground
 * PasswordField.disabledBackground
 * TitlePane.buttonHoverBackground
 * ScrollBar.hoverTrackColor
 * FormattedTextField.caretForeground
 * ToggleButton.selectedForeground
 * List.background
 * ToggleButton.tab.underlineColor
 * Objects.BlackText
 * TextArea.selectionBackground
 * MenuItem.selectionBackground
 * Label.foreground
 * Component.warning.focusedBorderColor
 * Spinner.background
 * FormattedTextField.foreground
 * Table.selectionInactiveForeground
 * PasswordField.capsLockIconColor
 * Button.foreground
 * InternalFrame.borderHighlight
 * TabbedPane.light
 * Button.disabledBackground
 * InternalFrame.closePressedForeground
 * Tree.icon.collapsedColor
 * TextArea.inactiveBackground
 * ToggleButton.shadow
 * OptionPane.background
 * ComboBox.buttonPressedArrowColor
 * Component.disabledBorderColor
 * Menu.disabledForeground
 * ToggleButton.disabledText
 * Button.toolbar.selectedBackground
 * TextField.darkShadow
 * ToolBar.hoverButtonGroupBackground
 * CheckBoxMenuItem.acceleratorSelectionForeground
 * Table.focusCellBackground
 * Button.disabledBorderColor
 * HelpButton.focusedBorderColor
 * FormattedTextField.inactiveBackground
 * Table.gridColor
 * ToolTip.background
 * MenuItem.checkBackground
 * EditorPane.foreground
 * CheckBox.icon.disabledCheckmarkColor
 * MenuItem.selectionForeground
 * Objects.Yellow
 * TabbedPane.closeHoverForeground
 * CheckBoxMenuItem.selectionBackground
 * Spinner.foreground
 * Tree.icon.openColor
 * CheckBox.icon.hoverBackground
 * PasswordField.background
 * InternalFrame.activeBorderColor
 * Button.hoverBackground
 * ScrollBar.background
 * Desktop.background
 * CheckBox.foreground
 * windowBorder
 * TabbedPane.underlineColor
 * TableHeader.bottomSeparatorColor
 * PasswordField.selectionBackground
 * Slider.pressedThumbColor
 * OptionPane.foreground
 * RootPane.activeBorderColor
 * Slider.tickColor
 * desktop
 * TabbedPane.closePressedForeground
 * EditorPane.selectionBackground
 * Button.default.pressedBackground
 * Component.accentColor
 * FormattedTextField.inactiveForeground
 * ToggleButton.selectedBackground
 * Button.disabledText
 * Button.toolbar.pressedBackground
 * ComboBox.selectionForeground
 * TextField.shadow
 * Label.background
 * SplitPaneDivider.oneTouchArrowColor
 * text
 * TitlePane.closeHoverBackground
 * Component.linkColor
 * CheckBoxMenuItem.selectionForeground
 * FormattedTextField.background
 * controlDkShadow
 * InternalFrame.borderDarkShadow
 * PasswordField.foreground
 * TextField.inactiveBackground
 * RadioButton.darkShadow
 * Objects.GreenAndroid
 * CheckBox.icon.borderColor
 * TabbedPane.foreground
 * control
 * ScrollBar.foreground
 * TextArea.disabledBackground
 * Button.focusedBorderColor
 * infoText
 * Menu.acceleratorForeground
 * Button.light
 * activeCaption
 * DesktopIcon.background
 * SplitPane.background
 * FormattedTextField.disabledBackground
 * Tree.selectionInactiveBackground
 * CheckBox.icon[filled].checkmarkColor
 * scrollbar
 * Button.hoverBorderColor
 * TextField.selectionBackground
 * Table.selectionForeground
 * Component.focusedBorderColor
 * EditorPane.background
 * info
 * TabbedPane.closeHoverBackground
 * TitlePane.closeHoverForeground
 * MenuItem.underlineSelectionColor
 * TabbedPane.focus
 * Menu.icon.disabledArrowColor
 * TextField.background
 * CheckBoxMenuItem.icon.disabledCheckmarkColor
 * Spinner.buttonBackground
 * Menu.background
 * ComboBox.foreground
 * TextField.inactiveForeground
 * Slider.shadow
 * RadioButton.light
 * Slider.highlight
 * Slider.thumbColor
 * InternalFrame.closeHoverForeground
 * ComboBox.buttonHighlight
 * CheckBox.background
 * CheckBox.icon.selectedBackground
 * PopupMenu.borderColor
 * ScrollBar.pressedButtonBackground
 * PopupMenu.background
 */